package au.net.hivemedia.quasimodo

import com.typesafe.scalalogging.LazyLogging

import BuildInfo._ // Generated by sbt-buildinfo (LiamHaworth)

/**
  * Created by Liam on 30/11/2015.
  */
object AppMain extends App with LazyLogging {

  logger.info(s"Starting Quasimodo v$version")

}
